export const SITE = {
  website: "https://ademfurkan.com/",
  author: "Adem Furkan Özcan",
  profile: "https://ademfurkan.com/",
  desc: "A digital journal where I share my writings",
  title: "Adem Furkan Özcan",
  ogImage: "og-image.png",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showBackButton: true,
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Istanbul",
} as const;
